export const Users = [
    {
      id:1,
      profilePicture: "assets/11.jpg",
      username: "Devansh Talwar",
    },
    {
      id:2,
      profilePicture: "assets/12.jpg",
      username: "Namrata Pathak",
    },
    {
      id:3,
      profilePicture: "assets/13.jpg",
      username: "Disha Ravel",
    },
    {
      id:4,
      profilePicture: "assets/14.jpg",
      username: "Sita Ghosh",
    },
    {
      id:5,
      profilePicture: "assets/15.jpg",
      username: "Kiran Ganesh",
    },
    {
      id:6,
      profilePicture: "assets/16.jpg",
      username: "Vaishnavi Kumari",
    },
    {
      id:7,
      profilePicture: "assets/17.jpg",
      username: "Anjali Verma",
    },
    {
      id:8,
      profilePicture: "assets/18.jpg",
      username: "Sujata Patel",
    },
    {
      id:9,
      profilePicture: "assets/19.jpg",
      username: "Bhupendra Singh",
    },
    {
      id:10,
      profilePicture: "assets/20.jpg",
      username: "Gopal Rao",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/Download.4.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/Download.3.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/Download.3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/Download.3.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/Download.3.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/Download.3.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/Download.3.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/Download.3.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/Download.3.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/Download.3.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];